kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels: 
      env: development
  template: 
    metadata:
      name: salespricepod
      labels:
        env: development
    spec:
      containers:
        - name: mlsalesprice
          image: kamli/salesprice #change name of docker image according to your docker image
          ports:
            - containerPort: 8080  
         
---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  selector:
    env: development
  type: NodePort #change according to your requirement as ClusterIP , NodePort , LoadBalancer
  ports:
  - name: name-of-the-port
    port: 8080  #Container port
    targetPort: 5000  #Pod port
