kind: Deployment
apiVersion: v1/apps
metadata:
  name: salespricedeployment
spec:
  replicas: 2
  selector:
    matchlabel:
      name: sales
  template:
    metadata:
      name: salespod
      label:
        name: sales
    spec:
      containers:
        - name: salescontainer
          image: 
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: sales
  ports:
  - port:   #containerport
    targetPort:   #pod port

